### ISSUE TITLE
[BUG] Black screen on update

### ISSUE THREAD

**Issue by P3ppe01** [fangkehou-team/BingGPT#14]
### Verify steps

- [X]  The version I'm running is up to date. 已安装最新版本. 
- [X]  I have tried right click and menu have shown 单击鼠标右键正常显示菜单 
- [X]  I can see the splash or loading screen. 可以正常看到屏幕中有显示加载或首页的内容 
- [X]  I have searched on the [issue tracker](……/) for a related issue. 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 

### BingGPT Version
软件版本

0.4.6  /  0.4.5

### What OS are you seeing the problem on?
操作系统/桌面环境

Windows

### What Architecture are you seeing the problem on?
系统指令集

x86

### Description

Hello, in the past few days, I've been experiencing difficulties with this version of the program. As soon as I open it, a screen with the message "Getting Cookies......Please wait for 10 or 20s" appears, and even after waiting for hours, it remains unchanged. I've tried closing and reopening the application without success. Subsequently, I attempted to download the previous version, 0.4.5, but the issue persists.

### Error Logs

This is what I see and what I can see as soon as I open the app.

![image](https://github.com/fangkehou-team/BingGPT/assets/127094941/ab64c3aa-6a07-4ab4-9558-aa64bc35aada)

### Steps To Reproduce

As soon as I open the application, this issue occurs. I hope you can resolve it as soon as possible :)

**Comment by lony2003** [comment]
can you right click in the app and select the "Open Devtools" and then head to the console page and take a screenshoot?

**Comment by P3ppe01** [comment]
This is what i can see on the console tab.
This error is logged multiple times.

Thnak u.

![image](https://github.com/fangkehou-team/BingGPT/assets/127094941/7d7bdc29-165d-4749-b4f4-81336a19148f)

**Comment by lony2003** [comment]
you didn‘t see any errors except that? Well, that's wired. Can you see the numbers in the console? Can you take a screenshoot?

**Comment by P3ppe01** [comment]
This is all i can see.

![image](https://github.com/fangkehou-team/BingGPT/assets/127094941/0269b543-4eb9-4c4b-8563-77fc2510f13c)


The last error keeps repeating indefinetively in the console.

**Comment by lony2003** [comment]
Well, I still don't know why. I think may be the app can not get cookies. So instead of letting the app wait forever, I'll let the app just jump to the main page after 50 seconds. I have made a update but I haven't released. You can go to the Github `Action` page of this repository and download the artifact that matchs your system in the `latest workflow run`, and then replace the `app.asar` in the app you installed with the `app.asar` in the downloaded compressed file.

You can help me test it.

> The last error keeps repeating indefinetively in the console.

As for the errors, It's Microsoft's problem and it doesn't affect the app's function, But every country has their own network environment, so I don't know why the app can not get the cookies (the number in the console has two meanings if you read the source code of this app, and both of them is 0 means that the cookies length of the Bing website is 0, the app can not deside if it has successfully got the cookies or not, so it waits forever).

**Comment by P3ppe01** [comment]
I apologize if I didn't respond immediately. Anyway, I replaced the `app.asar` file, and the issue has been resolved. Although the cookie prompt still appears, after a short while, it unlocks, and the system functions perfectly.
Thank u :)

**Comment by lony2003** [comment]
OK, I'll apply this change in the next release, but in case not everyone have this problem, I won't release it immediately, I'll wait till several changes have been applied.

Further informations, issues and PRs are welcomed. Thanks for contribution!
